manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: refil
      url-base: https://github.com/refil
    - name: ccarter
      url-base: https://github.com/ccarter
  projects:
    - name: zmk
      remote: ccarter
      revision: 360_last_device
      import: app/west.yml
  self:
    path: config
